project:
  type: website
  preview:
    browser: false
    watch-inputs: true
    navigate: false
website:
  title: "AI In The Loop"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/michaellosurdo
      - icon: twitter
        href: https://twitter.com
format:
  html:
    theme:
      light: theme/light.scss
      dark: theme/dark.scss
execute:
  freeze: auto
